Add parsing /etc/os-release file
ruby/etc pull request #33
Opened 2023-12-13 09:13 UTC by gromnitsky

Why?

* First of all, because [`os-release`][] is a file that resides in /etc.

* Second, the majority of Linux distros that are > 10 y.o. have it (including non-systemd-based ones).

* Even [FreeBSD adopted it][] in 2021 with release 13.

* Python has [`platform.freedesktop_os_release()`][] in its stdlib since v3.10 (2021).

* `os` rubygem contains the function that parses it, but poorly adheres to the os-release spec; for instance, does not ignore comments, does not unescape shell-escaped chars, &c.

* I think such a basic thing should be in the Ruby stdlib.

[`os-release`]: https://www.freedesktop.org/software/systemd/man/latest/os-release.html

[FreeBSD adopted it]: https://man.freebsd.org/cgi/man.cgi?query=os-release&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE&arch=default&format=html

[`platform.freedesktop_os_release()`]: https://docs.python.org/3.13/library/platform.html#platform.freedesktop_os_release

While searching through Github for how people parse this file, there are 3 camps:

1. shell:

       `source "/etc/os-release" && echo $ID`.chomp == 'fedora'

   which is simple but unsafe security-wise;

2. shell with an external commands like grep & sed;

3. ad hoc strategies: split by a newline then by '=' and remove surrounding quotes, or extract key-value pairs with a regex.

I propose this: parse os-release using Shellwords module, allow a user to parse it from any location, not just /etc, pre-fill the result with the defaults according to the Freedesktop spec.

(I'm not sure from where `Changelog` file, mentioned in `etc.gemspec`, should appear. It did not materialise when I run 'rake', so I had to remove the entry temporarily when testing 'gem build etc.gemspec'.)

2023-12-18 07:01 UTC, nobu requested changes
It seems that there is little necessity for belonging to `Etc` module.
Perhaps another module/gem would be better.

2023-12-18 07:03 UTC, nobu commented
For example.

```ruby
# -*- frozen-literal-string: true -*-

require 'shellwords'

module OSRelease
  FILES = ['/etc/os-release', '/usr/lib/os-release', '/etc/initrd-release']

  DEFAULS = {
    "linux" => {
      NAME: "Linux",
      ID: "linux",
      PRETTY_NAME: "Linux",
    }.freeze,
  }
  DEFAULS.default = {}.freeze

  def self.read(*src)
    src = FILES if src.empty?
    defauls = DEFAULS[RbConfig::CONFIG["target_os"]]
    src.each do |file|
      File.open(file) do |input|
        if result = parse(input, defauls.dup)
          return result
        end
      end
    end

    raise "No suitable sources"
  end

  def self.parse(input, result = {})
    input.each_line("\n").with_index(1) do |line, n|
      k, v = line.split("=", 2)
      next if !k or k.start_with?("#")
      if !v or /\A(?!\d)\w+\z/ !~ k or (v = v.shellsplit).size > 1
        input = input.path if input.respond_to?(:path)
        raise "malformed line at #{input}:#{n}: #{line}"
      end
      result[k] = v.first
    end
    result
  end
end
```

2023-12-19 04:14 UTC, gromnitsky commented
Thanks for the great feedback!

> It seems that there is little necessity for belonging to `Etc` module.
> Perhaps another module/gem would be better.

I wouldn't have bothered anyone had I not stumbled upon
`platform.freedesktop_os_release()` in python code.

Just to clarify: should I redo the PR to accommodate your notes, or
should I move all this to an external gem?

2023-12-19 10:29 UTC, olleolleolle commented on lib/etc.rb
> +    LINUX_DEFAULS = {
Typo, "default" missing its "t".

2023-12-29 11:48 UTC, nobu commented
Why not send a request to `os` gem?

2023-12-29 11:48 UTC, closed without merging